### Deadline for this HW -- 16th of  October, 23:59 (Moscow time). Please send your Jupyter notebook to email: natalya.vasileva@hse.ru. 
* It should contain all results printed. In other words, all cells must be "executed". 

* The result must be reproduced during verification (in Python 3).

* If some code has not been run or is working out with errors, then the item is not graded.

* A task submitted after the deadline is not accepted. You can send an unfinished task, completed items will be evaluated.

* The task is performed independently. If some students are caught cheating, all of them will automatically receive 0 points for this work. If you have found some specific code on the Internet that you are going to borrow, be sure to indicate it in the task properly - for sure you are not the only one who will find and use this information.

**Please name your file in the format "HW1_intro_to_python_Surname_Name.ipynb"**

In [68]:
import numpy as np
import scipy.stats
from scipy import linalg
import math 


#### Task 1 (0.25 points): Warm up

Write two versions of a function that takes a list my_list and the number $n$ and returns the sum of all list elements greater than or equal to $n$ -- with loop and with numpy 

Hint: you did the first version in the previous HW

In [69]:
def sum_greater_than(my_list, n):
    res = 0
    for x in my_list:
        if x >= n:
            res += x
            
    return res


def sum_greater_than_numpy(my_list, n):
    res = 0
    arr = np.array(my_list)
    tf = arr >= n 
    res = sum(arr*tf)
            
    return res

In [70]:
assert sum_greater_than([1, 2, 3], 2) == 5
assert sum_greater_than_numpy([-10, -1, -2, -3], -3) == -6

#### Task 2 (0.25 points): Leap year
You're given an integer number `year`. It is required to determine whether the year with this number is a leap year. If the year is a leap year, then output YES, otherwise output NO. Recall that according to the Gregorian calendar, a year is a leap year if its number is a multiple of 4, but not a multiple of 100, and also if it is a multiple of 400.

In [71]:
def is_leap_year(year):
    if year % 400 == 0:
        return 'YES'
    elif year % 100 == 0:
        return "NO"
    elif year % 4 == 0:
        return "YES"
    else:
        return "NO"

In [72]:
leaps = [2024, 2020, 2016, 2012, 2008, 2004, 2000, 1996, 1992, 1988, 1984, ]
not_leaps = [1700, 1800, 1900, 2100, 2200, 2300]

assert np.all(np.array([is_leap_year(year) for year in leaps]) == 'YES')

#### Task 3 (0.25 points): Is palindrome?
Determine whether the entered string is a palindrome (in other words, it is equally readable on both sides).

In [73]:
def is_palindrome(s):
    i = 0 
    j = len(s) - 1

    while i < j:
        if s[i] != s[j]:
            return False
        i += 1
        j -= 1

    return True

In [74]:
string = "anddna"
assert is_palindrome(string)

#### Task 4 (0.25 points): Decimal notation
You're given a float number. Find the number of digits in its decimal notation.

In [75]:
def decimal_notation(number):
    string = str(number)
    dec = string.split('.')
    
    return len(dec[1])

In [76]:
number = 32.323241245
assert decimal_notation(number) == 9, print(decimal_notation(number))

number = -0.234
assert decimal_notation(number) == 3, print(decimal_notation(number))

#### Task 5 (0.5 points): List of integers
You're given a list of integers. Write a function that returns a copy of this list, from which negative numbers are removed, and all other numbers are squared. Also, the returned sequence must be sorted in descending order.

In [77]:
def work_with_list(lst):
    copy = [x**2 for x in lst if x >=0]
    copy.sort(reverse=True)
    return copy

In [78]:
integer_list = [-555, 2, -4, 3, 44, 0, -3, 11]
res = work_with_list(integer_list)
assert res == [1936, 121, 9, 4, 0]
assert integer_list == [-555, 2, -4, 3, 44, 0, -3, 11]
assert id(res) != id(integer_list)

#### Task 6 (0.5 points): Dictionaries
The text is given as a string. Write a function that returns a dictionary, where the keys are unique words from this text, and the values are the number of times this word has occurred in the text. Assume that the words are separated by spaces.

In [79]:

def work_with_dicts(text):
    dictt = {}
    word = ''

    if text[-1] != ' ':
        text += ' '
    
    for letter in text:
        if letter != ' ':
            word += letter
        else:
            if word in dictt:
                dictt[word] += 1
                word = ''
            else:
                dictt[word] = 1
                word = ''

    return dictt

In [80]:
def work_with_dicts(text):
    lst = text.split(' ')
    dictt = {}

    for x in lst:
        if x in dictt:
            dictt[x] += 1
        else:
            dictt[x] = 1
            
    return dictt


In [81]:
text = "a b c aa a b c"
assert work_with_dicts(text) == {'aa': 1, 'c': 2, 'b': 2, 'a': 2}

#### Task 7 (3 points): Manipulations with matrices and OOP

Create a class *my_matrix* and implement four methods:
- *non_zero_diag_prod* should return a product of all non-zero diagonal elements of $X$, if all of them are 0s then return none
- *det_XTX* should return a determinant of $X^TX$
- *replace_nans* should find all *nan* values of $X$ and replace them with the arithmetic average of all the other elements of $X$. In the case of a matrix of all *nans* produced replaced by zeros.
- *calculate_stats* should calculate and print
 - determinant (*already implemented*)
 - trace
 - max and min elements
 - eigenvalues
 - inverse matrix

Hint: for *calculate_stats* just google corresponding numpy methods

Do it without using loops (if possible)

In [82]:
class my_matrix:
    
    def __init__(self, X):
        self.X = X
    
    def non_zero_diag_prod(self):
        i = 0 
        j = 0
        diag = []

        while i < len(self.X[0]) - 1:
            if self.X[i][j] > 0:
                diag.append(self.X[i][j])
            i += 1
            j += 1
        
        if len(diag) == 0:
            return None 
        else:
            prod = 1
            for x in diag:
                prod *= x 

            return prod

        
    
    def det_XTX(self):
        X_t = self.X.T

        XTX = X_t @ self.X

        det = np.linalg.det(XTX)

        return det

 
    
    def replace_nans(self):
        all_sum = 0

        for x in self.X:
            arr = np.array(x)

            cln_arr = np.nan_to_num(arr)
            inter_sum = sum(cln_arr)

            all_sum += inter_sum

        mean = all_sum / (len(self.X)*len(self.X[0]))

        matrix = []
        for y in self.X:
            arr = np.array(y)

            arr[np.isnan(arr)] = mean
            matrix.append(arr)

        
        return matrix
    

        
    def calculate_stats(self):
        print("Det = {}".format(np.linalg.det(self.X)), '\n')
        print("Trace = {}".format(np.trace(self.X)), '\n')

        max_el = float('-inf')
        min_el = float('inf')

        for x in self.X:

            max_el = max(max(x), max_el)
            min_el = min(min(x), min_el)
        
        print(f"Min element = {min_el}; max element = {max_el}", '\n')

        eigenvalues, eigenvectors = linalg.eig(self.X)
        inverse_matrix = linalg.inv(self.X)

        print(f'Eigenvalues = {eigenvalues}', '\n')
        print(f'Inverse matrix = {inverse_matrix}', '\n')
        


In [83]:
my_X = my_matrix(np.array([[10,2,3,4],[5,0,7,8],[9,10,11,12]]))

print(my_X.non_zero_diag_prod(), '\n')
print(my_X.det_XTX())

assert my_X.non_zero_diag_prod() == 110
assert np.abs(my_X.det_XTX() - (-1.5926383609604704e-09)) < 0.0000001

110 

0.0


In [84]:
my_X = my_matrix(np.array([[1,2,3,np.nan], [1,2,np.nan,3]]))
print("X = \n{}".format(my_X.X), '\n')
print("Result = \n{}".format(my_X.replace_nans()))

X = 
[[ 1.  2.  3. nan]
 [ 1.  2. nan  3.]] 

Result = 
[array([1. , 2. , 3. , 1.5]), array([1. , 2. , 1.5, 3. ])]


In [85]:
my_X = my_matrix(np.random.normal(10, 1, size=(5, 5)))
print("X = \n{}".format(my_X.X), '\n')
my_X.calculate_stats()

X = 
[[11.62434536  9.38824359  9.47182825  8.92703138 10.86540763]
 [ 7.6984613  11.74481176  9.2387931  10.3190391   9.75062962]
 [11.46210794  7.93985929  9.6775828   9.61594565 11.13376944]
 [ 8.90010873  9.82757179  9.12214158 10.04221375 10.58281521]
 [ 8.89938082 11.14472371 10.90159072 10.50249434 10.90085595]] 

Det = 73.80715080122845 

Trace = 53.98980961984621 

Min element = 7.698461303119718; max element = 11.74481176421648 

Eigenvalues = [49.96800328+0.j          3.14043406+0.j          1.27892705+0.j
 -0.19877738+0.57293373j -0.19877738-0.57293373j] 

Inverse matrix = [[ 0.07941692  0.57870693  0.47582557 -0.75309525 -0.35167133]
 [ 0.37335115  0.11816138 -0.42294919  0.02400836 -0.06915214]
 [-0.15699474 -0.07966787  0.25716001 -0.76293076  0.70576281]
 [-0.78157337  0.97418396  1.08958638 -0.68220473 -0.54292532]
 [ 0.46347787 -1.4521671  -1.26299523  2.01053249  0.26681129]] 



#### Task 8 (5 points): Option pricing

Here you should write a couple of functions for pricing 
- options of different types (European, American, Barrier) with
- different approaches (analytical, numerical schemes and MC simulations)

Implement everything as different functions (or write classes if you want) with different parameters, then compare results (where possible), plot convergence etc.

(2 points) Analytical formulas:

1. Implement analytical Black-Scholes formulas

2. Modify Black-Scholes formulas for dividends paying stocks

(2 points) Numerical schemes:

3. Implement Binomial pricing model

4. Modify program to price American option

(1 point) Monte Carlo methods:

5. Implement Monte Carlo simulation scheme for option pricing


##### Hint 1: This book could be very useful since it has all explanations and even pieces of code: *The Complete Guide To Option Pricing Formulas. Espen G. Haug*

##### Hint 2: You will have to make a very small modification to your Binomial tree model to price an American option 

In [86]:
# for the 1st task you can use this function to calculate CDF of a Normal distribution

scipy.stats.norm.cdf(0)

0.5

In [91]:
# analitical formula with out divs for call and put

def bs_option_price(S0, K, T, r, sigma, option_type='call'):

    d1 = (np.log(S0 / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)

    if option_type == 'call':
        call_price = S0 * scipy.stats.norm.cdf(d1) - K * np.exp(-r * T) * scipy.stats.norm.cdf(d2)
        return call_price
    
    if option_type == 'put':
        put_price = K * np.exp(-r * T) * scipy.stats.norm.cdf(-d2) - S0 * scipy.stats.norm.cdf(-d1)
        return put_price 
    
    else:
        print(f"option_type argument must be ether 'call' or 'put'")

    

# analitical formula with divs for call and for put 
# where delta is amount of divs that will be payed from 0 to T

def bs_call_price(S0, K, T, r, sigma, delta):
    d1 = (np.log(S0 / K) + (r - delta + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    call_price = S0 * np.exp(-delta * T) * scipy.stats.norm.cdf(d1) - K * np.exp(-r * T) * scipy.stats.norm.cdf(d2)
    return call_price


In [88]:
def euro_vanilla_binomial(S, K, T, r, sigma, option='call', n=10):

    up = np.exp(sigma * np.sqrt(T/n))
    down = np.exp(-sigma * np.sqrt(T/n))

    # this is the correct formula for risk-neutral probability of up state in binomial pricing formula 
    q = (np.exp(r * (T / n)) - down) / (up - down)

    option_price = 0

    #here i is a number of up movements
    for i in range(n, -1, -1):

        bin_coef= math.factorial(n) / (math.factorial(n - i) * math.factorial(i))

        prob = (q**i) * ((1 - q)**(n-i))

        stock_price = S * up**i * down**(n-i)

        if option == 'call':
            payoff = max(stock_price - K, 0)

        elif option == 'put':
            payoff = max(K - stock_price, 0)
        
        else:
            print("option argument must be ether 'call' or 'put'" )

        path_value = bin_coef*prob*payoff

        #print(f'bin_coef: {bin_coef}; prob: {prob}; stock_price: {stock_price}; path_value: {path_value}')

        option_price += path_value

    #correct discounting is not the exponential one but the regular as we have discrete time intervals
    return option_price * np.exp(-r * T)


def euro_vanilla_mc(S, K, T, r, sigma, option='call', n=10, n_samples=10**3):
        
    up = np.exp(sigma * np.sqrt(T/n))
    down = np.exp(-sigma * np.sqrt(T/n))

    q = (np.exp(r * (T / n)) - down) / (up - down)

    cum_sum = 0
        
    for _ in range(n_samples):

        path = np.random.binomial(1, p=q, size= (n))
        i = sum(path)
        
        stock_price = S * up**i * down**(n-i)

        if option == 'call':
            payoff = max(stock_price - K, 0)

        elif option == 'put':
            payoff = max(K - stock_price, 0)
        
        else:
            print("option argument must be ether 'call' or 'put'" )

        cum_sum += payoff

    option_price = (cum_sum / n_samples) * (r**n)
    
    return option_price

In [100]:
#AMERICAN OPTION

#since we know that its never optimal to exercise american call option on non paying divident stock befor the maturity, its price will be the same as for eupopean one
#the difference will arrize if we have dividents
#since we have no even a single clue about what structure of div payoffs we have, I assume my own structure 
#Divs will be payed only if stock hits 110% of its initial value, and and amount of divs is 5%
#Divs is a form of repaying euqity to euqity holders, so if divs are payed then the value of stock will decrease by this amount
#Divs are not payed to the option holder 
#Divs payed befor option can be exicuted
#So now we actually have a trade off between exercise today or wait untill maturity 

def american_option_bin(S, K, T, r, sigma, option='call', n=10,):

    up = np.exp(sigma * np.sqrt(T/n))
    down = np.exp(-sigma * np.sqrt(T/n))

    q = (np.exp(r * (T / n)) - down) / (up - down)
    
    optimal_values = [] 

    for i in range(n, 0, -1):

        if not optimal_values:

            stock_prices = []
            for x in range(i+1):
                stock_price = S * (up**(i - x)) * (down**x)
                
                #divs rule:
                if stock_price > S * 1.1:
                    stock_price -= stock_price * 0.05

                stock_prices.append(stock_price)
            
            payoffs = []
            if option == 'call':

                for price in stock_prices:
                    payoff = max(price - K, 0)
                    payoffs.append(payoff)

            elif option == 'put':
                for price in stock_prices:
                    payoff = max(K - price, 0)
                    payoffs.append(payoff)

            else: 
                print("option argument must be ether 'call' or 'put' ")
                return
        else:
            payoffs = optimal_values
        
        risk_neutral_expectations = []
        for y in range(i):
            expect = ((q * payoffs[y]) + (q * payoffs[y+1])) / (1 + r)
            risk_neutral_expectations.append(expect)

        prev_prices = []
        for j in range(i):
            prev_price = S * (up**((i-1) - j)) * (down**j)

            #divs rule again
            if prev_price > S * 1.1:
                prev_price -= prev_price * 0.05
            
            prev_prices.append(prev_price)

        prev_payofs = []
        if option == 'call':

            for price in prev_prices:
                payoff = max(price - K, 0)
                prev_payofs.append(payoff)

        elif option == 'put':
            for price in prev_prices:
                payoff = max(K - price, 0)
                prev_payofs.append(payoff)
        
        #optimal dicision now 
        optimal_values = [] 
        for l in range(i):

            optimal_value = max(prev_payofs[l], risk_neutral_expectations[l])

            #lets print some validation info here
            if prev_payofs[l] > risk_neutral_expectations[l]:
                print(f"In {i-1} period in {i-1-l} steps up its optimal to exercise option. Optimal value: {optimal_value}")
            else:
                print(f"In {i-1} period in {i-1-l} steps up its optimal to wait. Optimal value: {optimal_value}")

            optimal_values.append(optimal_value)
    
    return optimal_values
            

In [95]:
bs_option_price(S, K, T, r, sigma, option)

2.5127067408963075

In [101]:
np.random.seed(1)
S = 50
K = 100
T = 1
r = 0.05
q = 0.1
sigma = 0.25
n = 10
n_samples = 10**3
option = 'put'


assert abs(bs_option_price(S, K, T, r, sigma, option) - 45.15029495944084) < 0.001
assert abs(euro_vanilla_binomial(S, K, T, r, sigma, option, n) - 45.134971983328526) < 0.001
american_option_bin(S, K, T, r, sigma, option, n)

In 9 period in 9 steps up its optimal to wait. Optimal value: 5.165089962484449
In 9 period in 8 steps up its optimal to exercise option. Optimal value: 17.390201320684156
In 9 period in 7 steps up its optimal to exercise option. Optimal value: 29.471673844537605
In 9 period in 6 steps up its optimal to exercise option. Optimal value: 39.78626180169168
In 9 period in 5 steps up its optimal to wait. Optimal value: 46.005690615089236
In 9 period in 4 steps up its optimal to exercise option. Optimal value: 53.800634514008266
In 9 period in 3 steps up its optimal to exercise option. Optimal value: 60.55717397617531
In 9 period in 2 steps up its optimal to exercise option. Optimal value: 66.32558676119865
In 9 period in 1 steps up its optimal to exercise option. Optimal value: 71.25038387734669
In 9 period in 0 steps up its optimal to exercise option. Optimal value: 75.45494196621827
In 8 period in 8 steps up its optimal to wait. Optimal value: 10.996564151847576
In 8 period in 7 steps up i

[50.0]