### Deadline for this HW -- 16th of  October, 23:59 (Moscow time). Please send your Jupyter notebook to email: natalya.vasileva@hse.ru. 
* It should contain all results printed. In other words, all cells must be "executed". 

* The result must be reproduced during verification (in Python 3).

* If some code has not been run or is working out with errors, then the item is not graded.

* A task submitted after the deadline is not accepted. You can send an unfinished task, completed items will be evaluated.

* The task is performed independently. If some students are caught cheating, all of them will automatically receive 0 points for this work. If you have found some specific code on the Internet that you are going to borrow, be sure to indicate it in the task properly - for sure you are not the only one who will find and use this information.

**Please name your file in the format "HW1_intro_to_python_Surname_Name.ipynb"**

In [1]:
import numpy as np
import scipy.stats

#### Task 1 (0.25 points): Warm up

Write two versions of a function that takes a list my_list and the number $n$ and returns the sum of all list elements greater than or equal to $n$ -- with loop and with numpy 

Hint: you did the first version in the previous HW

In [2]:
def sum_greater_than(my_list, n):
    res = 0
            
    return res


def sum_greater_than_numpy(my_list, n):
    res = 0
            
    return res

In [ ]:
assert sum_greater_than([1, 2, 3], 2) == 5
assert sum_greater_than_numpy([-10, -1, -2, -3], -3) == -6

#### Task 2 (0.25 points): Leap year
You're given an integer number `year`. It is required to determine whether the year with this number is a leap year. If the year is a leap year, then output YES, otherwise output NO. Recall that according to the Gregorian calendar, a year is a leap year if its number is a multiple of 4, but not a multiple of 100, and also if it is a multiple of 400.

In [ ]:
def is_leap_year(year):
    ...
    return ...

In [ ]:
leaps = [2024, 2020, 2016, 2012, 2008, 2004, 2000, 1996, 1992, 1988, 1984, ]
not_leaps = [1700, 1800, 1900, 2100, 2200, 2300]

assert np.all(np.array([is_leap_year(year) for year in leaps]) == 'YES')

#### Task 3 (0.25 points): Is palindrome?
Determine whether the entered string is a palindrome (in other words, it is equally readable on both sides).

In [ ]:
def is_palindrome(s):
    ...
    return ...

In [ ]:
string = "anddna"
assert is_palindrome(string)

#### Task 4 (0.25 points): Decimal notation
You're given a float number. Find the number of digits in its decimal notation.

In [ ]:
def decimal_notaion(number):
    ...
    return ...

In [ ]:
number = 32.323241245
assert decimal_notation(number) == 9, print(decimal_notation(number))

number = -0.234
assert decimal_notation(number) == 3, print(decimal_notation(number))

#### Task 5 (0.5 points): List of integers
You're given a list of integers. Write a function that returns a copy of this list, from which negative numbers are removed, and all other numbers are squared. Also, the returned sequence must be sorted in descending order.

In [1]:
def work_with_list(lst):
    ...
    return ...

In [ ]:
integer_list = [-555, 2, -4, 3, 44, 0, -3, 11]
res = work_with_list(integer_list)
assert res == [1936, 121, 9, 4, 0]
assert integer_list == [-555, 2, -4, 3, 44, 0, -3, 11]
assert id(res) != id(integer_list)

#### Task 6 (0.5 points): Dictionaries
The text is given as a string. Write a function that returns a dictionary, where the keys are unique words from this text, and the values are the number of times this word has occurred in the text. Assume that the words are separated by spaces.

In [ ]:
def work_with_dicts(text):
    ...
    return ...

In [ ]:
text = "a b c aa a b c"
assert work_with_dicts(text) == {'aa': 1, 'c': 2, 'b': 2, 'a': 2}

#### Task 7 (3 points): Manipulations with matrices and OOP

Create a class *my_matrix* and implement four methods:
- *non_zero_diag_prod* should return a product of all non-zero diagonal elements of $X$, if all of them are 0s then return none
- *det_XTX* should return a determinant of $X^TX$
- *replace_nans* should find all *nan* values of $X$ and replace them with the arithmetic average of all the other elements of $X$. In the case of a matrix of all *nans* produced replaced by zeros.
- *calculate_stats* should calculate and print
 - determinant (*already implemented*)
 - trace
 - max and min elements
 - eigenvalues
 - inverse matrix

Hint: for *calculate_stats* just google corresponding numpy methods

Do it without using loops (if possible)

In [12]:
class my_matrix:
    
    def __init__(self, X):
        self.X = X
    
    def non_zero_diag_prod(self):
        pass
    
    def det_XTX(self):
        pass
    
    def replace_nans(self):
        pass
        
    def calculate_stats(self):
        print("Det = {}".format(np.linalg.det(self.X)), '\n')
        pass
        


In [9]:
my_X = my_matrix(np.array([[10,2,3,4],[5,0,7,8],[9,10,11,12]]))

print(my_X.non_zero_diag_prod(), '\n')
print(my_X.det_XTX())

assert my_X.non_zero_diag_prod() == 110
assert np.abs(my_X.det_XTX() - (-1.5926383609604704e-09)) < 0.0000001

110 

-1.5926383609604704e-09


In [10]:
my_X = my_matrix(np.array([[1,2,3,np.nan], [1,2,np.nan,3]]))
print("X = \n{}".format(my_X.X), '\n')
print("Result = \n{}".format(my_X.replace_nans()))

X = 
[[ 1.  2.  3. nan]
 [ 1.  2. nan  3.]] 

Result = 
[[1. 2. 3. 2.]
 [1. 2. 2. 3.]]


In [11]:
my_X = my_matrix(np.random.normal(10, 1, size=(5, 5)))
print("X = \n{}".format(my_X.X), '\n')
my_X.calculate_stats()

X = 
[[12.81701314 11.15296323  8.93198104 11.99438527 10.97825266]
 [ 9.97896711  8.81383582  8.96571962 10.27347793  9.24774697]
 [11.14311662 10.23763392  9.65004651  9.03951862 10.25342139]
 [ 8.339493   10.39582388 10.38104754  8.38488098  9.80390921]
 [ 9.58502551  9.55729873  8.95885421  8.26081924 10.42028095]] 

Det = -160.58884687721886 

Trace = 50.086057394268295 

Max elem = 12.817013137228646 and Min elem = 8.260819243904509 

Eigenvalues = 
[49.56051759+0.j         -1.24253994+0.j          0.4423054 +1.66015197j
  0.4423054 -1.66015197j  0.88346895+0.j        ] 

Inv matrix = 
[[-0.11019576 -0.01716479  0.65520148 -0.29981078 -0.23130342]
 [ 0.51517842 -0.66578793 -0.04728953  0.50007089 -0.3758527 ]
 [-0.45737739  0.38114647  0.4070786   0.02135264 -0.2770395 ]
 [ 0.15480173  0.29211027 -0.46300184  0.08625866 -0.04790019]
 [-0.10063996  0.06717221 -0.54224508 -0.269618    0.92961381]] 



#### Task 8 (5 points): Option pricing

Here you should write a couple of functions for pricing 
- options of different types (European, American, Barrier) with
- different approaches (analytical, numerical schemes and MC simulations)

Implement everything as different functions (or write classes if you want) with different parameters, then compare results (where possible), plot convergence etc.

(2 points) Analytical formulas:

1. Implement analytical Black-Scholes formulas

2. Modify Black-Scholes formulas for dividends paying stocks

(2 points) Numerical schemes:

3. Implement Binomial pricing model

4. Modify program to price American option

(1 point) Monte Carlo methods:

5. Implement Monte Carlo simulation scheme for option pricing


##### Hint 1: This book could be very useful since it has all explanations and even pieces of code: *The Complete Guide To Option Pricing Formulas. Espen G. Haug*

##### Hint 2: You will have to make a very small modification to your Binomial tree model to price an American option 

In [ ]:
# for the 1st task you can use this function to calculate CDF of a Normal distribution

scipy.stats.norm.cdf(0)

In [29]:
# and these for Monte carlo methods 

print(np.linspace(0, 1, 8))
print(np.random.normal(size=8))

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]
[-0.11281739  0.3651981  -0.7470612  -0.73868878  0.34377732  0.01845088
  0.07193886  1.50384287]


In [24]:
def euro_vanilla_analytical(S, K, T, r, sigma, option='call'):
    
    result = S - K
        
    return result


def euro_vanilla_binomial(S, K, T, r, sigma, option='call', n_periods=10):
    
    return 0


def euro_vanilla_mc(S, K, T, r, sigma, option='call', n_periods=10, n_samples=10**3):
    
    return 0

In [ ]:
np.random.seed(1)
S = 50
K = 100
T = 1
r = 0.05
q = 0.1
sigma = 0.25
n_periods = 10
n_samples = 10**3
option = 'put'

assert abs(euro_vanilla_analytical(S, K, T, r, sigma, option) - 45.15029495944084) < 0.001
assert abs(euro_vanilla_binomial(S, K, T, r, sigma, option, n_periods) - 45.134971983328526) < 0.001